# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: blue_arm
  joint_model_group_pose: zero_pose
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
# blue_arm:
#   joint_state_controller:
#     type: joint_state_controller/JointStateController
#     publish_rate: 50
#   controller_list:
#     []
#   blue_arm_controller:
#     type: effort_controllers/JointVelocityController
#     joints:
#       - joint_1
#       - joint_2
#       - joint_3
#       - joint_4
#       - joint_5
#       - joint_6
#       - joint_7
#     gains:
#       joint_1:
#         p: 1000
#         d: 50
#         i: 0
#       joint_2:
#         p: 1000
#         d: 50
#         i: 0
#       joint_3:
#         p: 800
#         d: 40
#         i: 0
#       joint_4:
#         p: 800
#         d: 40
#         i: 0
#       joint_5:
#         p: 500
#         d: 25
#         i: 0
#       joint_6:
#         p: 500
#         d: 25
#         i: 0
#       joint_7:
#         p: 500
#         d: 25
#         i: 0

controller_list:
  - name: "blue_arm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
      
# controller_list:
#   - name: "joint_group_position_controlle"
#     type: std_msgs/Float64MultiArray
#     default: true
#     joints:
#       - joint_1
#       - joint_2
#       - joint_3
#       - joint_4
#       - joint_5
#       - joint_6
#       - joint_7
  # - name: "joint_1"
  #   type: std_msgs/Float64
  #   default: true
  #   joint: joint_1
  # - name: "joint_2"
  #   type: std_msgs/Float64
  #   default: true
  #   joint: joint_2
  # - name: "joint_3"
  #   type: std_msgs/Float64
  #   default: true
  #   joint: joint_3
  # - name: "joint_4"
  #   type: std_msgs/Float64
  #   default: true
  #   joint: joint_4
  # - name: "joint_5"
  #   type: std_msgs/Float64
  #   default: true
  #   joint: joint_5
  # - name: "joint_6"
  #   type: std_msgs/Float64
  #   default: true
  #   joint: joint_6
  # - name: "joint_7"
  #   type: std_msgs/Float64
  #   default: true
  #   joint: joint_7



# joint_1:
#   type: velocity_controllers/JointVelocityController
#   joint: joint_1
#   pid: {p: 1000, i: 0.0, d: 50.0}

# joint_2:
#   type: velocity_controllers/JointVelocityController
#   joint: joint_2
#   pid: {p: 1000, i: 0.0, d: 50.0}

# joint_3:
#   type: velocity_controllers/JointVelocityController
#   joint: joint_3
#   pid: {p: 800, i: 0.0, d: 40.0}

# joint_4:
#   type: velocity_controllers/JointVelocityController
#   joint: joint_4
#   pid: {p: 800, i: 0.0, d: 40.0}

# joint_5:
#   type: velocity_controllers/JointVelocityController
#   joint: joint_5
#   pid: {p: 500, i: 0.0, d: 25.0}

# joint_6:
#   type: velocity_controllers/JointVelocityController
#   joint: joint_6
#   pid: {p: 500, i: 0.0, d: 25.0}

# joint_7:
#   type: velocity_controllers/JointVelocityController
#   joint: joint_7
#   pid: {p: 500, i: 0.0, d: 25.0}

# blue_arm:
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

blue_arm_controller:
  type: position_controllers/JointTrajectoryController
  # type: velocity_controllers/JointVelocityController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint_1: {trajectory: 0.1, goal: 0.1}
      joint_2: {trajectory: 0.1, goal: 0.1}
      joint_3: {trajectory: 0.1, goal: 0.1}
      joint_4: {trajectory: 0.1, goal: 0.1}
      joint_5: {trajectory: 0.1, goal: 0.1}
      joint_6: {trajectory: 0.1, goal: 0.1}
      joint_7: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  gains:
    joint_1:
      p: 1000
      d: 50
      i: 0
    joint_2:
      p: 1000
      d: 50
      i: 0
    joint_3:
      p: 800
      d: 40
      i: 0
    joint_4:
      p: 800
      d: 40
      i: 0
    joint_5:
      p: 500
      d: 25
      i: 0
    joint_6:
      p: 500
      d: 25
      i: 0
    joint_7:
      p: 500
      d: 25
      i: 0

joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  # type: velocity_controllers/JointGroupVelocityController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7